development:
  adapter: postgresql
  encoding: unicode
  database: vote-a-tron_development
  pool: 5
  username: postgres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: vote-a-tron_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: vote-a-tron_production
  pool: 5
  username: postgres
  password:
